spring:
  application:
    name: movie-info-service
server:
  port: 8080

api:
  key:

management:
  endpoints:
    web:
      exposure:
        include: auditevents,beans,conditions,configprops,env,health,httptrace,info,logfile,mappings,metrics,prometheus
