k8-application:
  containers:
    movie-info-service:
      image:
        name: utsabroy/movie-info-service
        tag: 8e9ff6d
      ports:
        - 8080
      environment:
        PORT: 8080
      readinessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
  service:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /actuator/health
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 8080